name: cnj
description: Chicder.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  swipable_stack: ^2.0.0
  url_launcher: ^6.1.2
  get: ^4.6.5
  connectivity_plus: ^2.3.4
  firebase_crashlytics: ^2.8.2
  firebase_core: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
